### ISSUE TITLE
symengine

### ISSUE THREAD

**Issue by daleydeng** [laurentkneip/polyjam#1]
Symengine seems to be a good C++ symbolic processing library, will it be considered to replace the low level processing in polyjam?

**Comment by laurentkneip** [comment]
I looked into a few symbolic computation toolboxes, and it perhaps makes sense to replace the Symbolic field implementation with an existing, more established library. I do however not have this on my own todo list, as the current functionality is enough for my needs. You can come up with a PR if motivated, but please keep in mind that any newly introduced dependencies should be broadly supported. Issue closed for now.
